format = """
[](#264653)\
$username\
[](bg:#2A9D8F fg:#264653)\
$directory\
[](fg:#2A9D8F bg:#E9C46A)\
$git_branch\
$git_status\
[](fg:#E9C46A bg:#F4A261)\
$c\
$elixir\
$elm\
$golang\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#F4A261 bg:#E76F51)\
$docker_context\
[](fg:#E76F51 bg:#E24E29)\
$time\
[ ](fg:#E24E29)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false
command_timeout = 1500

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "fg:white bg:#264653"
style_root = "fg:white bg:#264653"
format = '[$user ]($style)'

[directory]
style = "fg:black bg:#2A9D8F"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[docker_context]
symbol = " "
style = "fg:white bg:#E76F51"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "fg:black bg:#F4A261"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "fg:black bg:#F4A261"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "fg:black bg:#E9C46A"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:black bg:#E9C46A"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "fg:black bg:#F4A261"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "fg:black bg:#F4A261"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "fg:black bg:#F4A261"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "fg:black bg:#F4A261"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "fg:black bg:#F4A261"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "fg:black bg:#F4A261"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "fg:black bg:#F4A261"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:black bg:#E24E29"
format = '[ ♥ $time ]($style)'
