{...}: {
  # Auto-generated by nixos-generate-config; kept underscore-prefixed so
  # import-tree doesn't try to import it directly as a flake-parts module.
  flake.nixosModules.frameworkDesktopHardware = import ./_hardware-configuration.nix;
}
